export const RoutePaths = {
    ROOT: '/',
    HOME: 'home',
    TESTIMONIALS:'testimonials',
    LOGINFORM: 'loginForm',
    ABOUT: 'about',
    GALLERY: 'gallery',
    WALLET: 'wallet',
    ENROLLEMENT: 'enrollement',
    ENROLLEMENTLIST: 'enrollementList',
    EMPLOYMENTLIST: 'employmentList',
    REENROLLEMENT: 'reEnrollement',
    REENROLLEMENTLIST: 'reEnrollementList',
    EMPLOYMENT: 'employment',
    DONATION: 'donation',
    PAYMENT: 'payment',
    FEES: 'fees',
    SERMON: 'sermon',
    PLAYGROUND: 'playGround',
    CONTACTLIST: 'contactList',
    CONTACT: 'contact',
    ADMIN: 'admin',
    SETTINGS: 'settings',
    HOMEPAGE: 'homePage',
    CREATEPOST: 'createPost',

};
   